### ISSUE TITLE
Can't catch 404/500 errors

### ISSUE THREAD

**Issue by greggilbert** [expressjs/vhost#14]
Hey. Quick question: where do you recommend putting the functions to do error handling? Express 4 documentation says to use `app.use(function(err, req, res, next)` after all the regular routing goes in. I had it in my vhost-specific files, but it's not properly catching 404s. I moved it up to the to `app.js` as below, but it still doesn't work for some reason. Sample:

```
var firstApp = require('./first/app');
var secondApp = require('./second/app');
// ...
app.use(vhost('app.test', secondApp))
    .use(vhost(/.*/, firstApp));
// ...
app.use(function(err, req, res, next) {
  res.status(err.status || 500);
  res.render('error', {
    message: err.message,
    error: {}
  });
});
```

And then `first/app.js` and `second/app.js` are just creating `express()` apps and then exporting them. Any idea on how to properly do error catching?

**Comment by dougwilson** [comment]
Hi! At first I was thinking it was a question for the `vhost` module, but I'm not sure if it's just a general Express question instead, haha.

So in Express, a 404 is not an "error", rather it's just the falling through of the route matching. This means to "catch" 404s, you simply define a route that catches everything at the end on your stack:
```js
app.use(function(req, res, next) { // i catch 404s
  res.status(404);
  res.render('not_found');
});

app.use(function(err, req, res, next) { // i catch errors, but 404 is not an error
  res.status(err.status || 500);
  res.render('error', {
    message: err.message,
    error: {}
  });
});
```

**Comment by greggilbert** [comment]
Makes sense. So here's something interesting: taking the `app.use` for 404s as you mentioned above and dropping it into a vhost overrides the top level one for _all_ vhosts. So I guess that means that there's no way to customize the default route on a per-vhost basis?

**Comment by dougwilson** [comment]
Hi @greggilbert ! Unfortunately I don't follow what you mean. Can you provide a code example demonstrating?

**Comment by greggilbert** [comment]
Sure! I've created a Gist [here](https://gist.github.com/greggilbert/47ab9981720f8dc31db1). Here's what I'm getting at: because there's a default route in `first/app.js`, the default route in the main `app.js` will never fire. In fact, the default route in `first/app.js` takes over the default routes for _all_ vhosts. So if anything falls through in `second/app.js`, it uses the default in `first`.

Did that help, or did I make that more confusing? :/

**Comment by dougwilson** [comment]
Hi! The issue is your second-app is taking over, because you have your `vhost` declaration purposely capturing all requests for some reason. i.e. you used `/.*/` which will capture _everything_, thus the one in the main file will ever get hit...

**Comment by dougwilson** [comment]
Basically, as far as routing in concerned, `.use(vhost(/.*/, secondApp))` is identical to `.use(secondApp)`. Why are you using `/.*/`?

**Comment by greggilbert** [comment]
Well, I'm trying to build something where I can send a bunch of domains at Express, e.g. `a.foo.com` and `b.bar.com`, and catch them all. Rather than maintaining a strict whitelist, I thought it better to open it up to everything and potentially deal with domain-specific logic further down the line. 

Anyway, without the `/.*` catchall, this works as you've described. I guess it's a bit weird to me that in this case:

```
app.use(vhost('app.v.test', firstApp))
  .use(vhost('*.v.test', secondApp));
```

where `app` and `firstApp` (but not `secondApp`) have defaults, you get the following behavior:

`app.v.test/fail` -> firstApp's default, as expected
`hi.v.test/fail` -> firstApp's default and not app's

Put another way, hitting a route that matches the vhost for secondApp but no route there means that it falls back to firstApp, and not to the parent app.

**Comment by dougwilson** [comment]
You are making sense! Yes, the reason it works like this is because it's how Express works: matching works strictly in a linear fashion in the order you define things. This means if you defined both `app.v.test` and `*.v.test`, the matching order is the exact your you `.use()` them--they are not aware of each other and have no way to understand what is more specific.

>  hi.v.test/fail -> firstApp's default and not app's

Running your code snippet does not reproduce this behavior for me. Perhaps you made a typo somewhere? Calling with `Host: hi.v.test` does not enter `firstApp`, since it does not match `app.v.test`--it enters `secondApp` since it does match `*.v.test`.

**Comment by dougwilson** [comment]
P.S. I closed the issue only because the main question is answered, not necessarily because you cannot ask more questions :)

Also, if you do happen to think there is a bug or something, please do try to provide a full single file, as it makes it clear exactly what code I should be running to reproduce, otherwise misunderstanding typically occur somewhere down the line :)

**Comment by greggilbert** [comment]
Your first post nailed it: that it's entirely in linear fashion. I did mess up the snippet a bit; in my real case, the 404 fallthrough was on secondApp, not firstApp - so in that case, 404s for both firstApp and secondApp were getting the secondApp fallthrough.

I guess I was expecting that the routing rules when using vhosts were more self-contained. It's totally fine that's it's not - just a thought on my end. Thanks for working through this with me!

**Comment by dougwilson** [comment]
Hi @greggilbert, it's no problem! I have had some cases where I also did not want it to fall-though. Typically I have uses the pattern of the following:
```js
app.use(vhost('app.test', function (req, res) {
  secondApp(req, res)
}))
```
i.e. preventing the third argument from being passed to the `secondApp`, so that it will 404 for anything that gets into there.

I am almost thinking now that maybe an optional `options` argument can be added as the third argument, perhaps making it possible to do that pattern by configuration, if it is common. For example: `vhost(hostname, secondApp, { fallthrough: false })`. From community feedback, I semi-recently added the `fallback` as an option in `serve-static`, so perhaps it's time to add something similar here.

Thoughts?
