### ISSUE TITLE
Its not working without adding the subdomain in /etc/host

### ISSUE THREAD

**Issue by tbhaxor** [expressjs/vhost#38]
Hi, I want to implement it in an application that tends to assign each user its subdomain.
Since I can't edit `/etc/hosts` every time and the vhost is not working for me for the subdomains that are not listed in `/etc/hosts`

**Comment by dougwilson** [comment]
This module works only once the request actually makes to to your server. In order to make it to your server, your web browser needs to use DNS to resolve a given hostname to an IP address. By editing your `/etc/hosts` file, this gets your web browser to resolve the name. The other method is to actually buy a domain name and then set up your provider's DNS to set each subdomain you want to point to the same server IP, in which then this module will help route.

I hope that helps.
